steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/cult-creative-421007/github.com", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/cult-creative-421007/github.com"]
