steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/cult-creative-421007/github.com:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/cult-creative-421007/github.com:$COMMIT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "cult-creative-landing",
        "--image",
        "gcr.io/cult-creative-421007/github.com:$COMMIT_SHA",
        "--region",
        "asia-southeast1",
      ]

serviceAccount: "cloud-run-landing@cult-creative-421007.iam.gserviceaccount.com"

images:
  - "gcr.io/cult-creative-421007/github.com:$COMMIT_SHA"

options:
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"
